use std::path::{Path, PathBuf};

/// Embed every `locales/*.json` into the binary.
///
/// Generated rather than hand-listed so adding a language is only ever
/// "drop in locales/<code>.json": the file list is discovered here, and
/// `i18n.rs` reads whatever this produces.
fn generate_locales(locales_dir: &Path, out: &Path) {
    let mut entries: Vec<(String, PathBuf)> = std::fs::read_dir(locales_dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {}", locales_dir.display(), e))
        .flatten()
        .filter_map(|entry| {
            let path = entry.path();
            if path.extension()?.to_str()? != "json" {
                return None;
            }
            let code = path.file_stem()?.to_str()?.to_string();
            Some((code, path))
        })
        .collect();
    // Stable order so the generated file (and any UI listing) is stable
    entries.sort_by(|a, b| a.0.cmp(&b.0));
    assert!(
        !entries.is_empty(),
        "no locale files in {}",
        locales_dir.display()
    );

    let mut code = String::from(
        "// @generated by build.rs from locales/*.json — do not edit\n\
         pub static LOCALES: &[(&str, &str)] = &[\n",
    );
    for (lang, path) in &entries {
        // Rebuild when a locale changes, and include it verbatim
        println!("cargo:rerun-if-changed={}", path.display());
        code.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            lang,
            path.canonicalize().unwrap_or_else(|_| path.clone())
        ));
    }
    code.push_str("];\n");
    std::fs::write(out, code).expect("write generated locales");
}

/// Bake the distribution channel into the binary.
///
/// The Store copy and the downloaded copy have to be told apart at runtime
/// because only one of them may update itself: two update paths pointing at
/// the same install is how a user ends up on a version neither channel
/// thinks it shipped. Nothing distinguishes the two binaries otherwise, so
/// the channel has to come from the build, not from config a user could
/// flip.
fn emit_release_channel() {
    const KNOWN: [&str; 2] = ["download", "store"];
    println!("cargo:rerun-if-env-changed=CONDUIT_RELEASE_CHANNEL");
    let channel = std::env::var("CONDUIT_RELEASE_CHANNEL").unwrap_or_else(|_| "download".into());
    // A typo would otherwise build a self-updating binary and ship it to the
    // Store, which is the one outcome this whole mechanism exists to prevent.
    assert!(
        KNOWN.contains(&channel.as_str()),
        "CONDUIT_RELEASE_CHANNEL must be one of {:?}, got {:?}",
        KNOWN,
        channel
    );
    println!("cargo:rustc-env=CONDUIT_RELEASE_CHANNEL={}", channel);
}

fn main() {
    emit_release_channel();

    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let locales = manifest
        .parent()
        .expect("workspace root")
        .join("locales");
    println!("cargo:rerun-if-changed={}", locales.display());

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("out dir")).join("locales.rs");
    generate_locales(&locales, &out);

    tauri_build::build()
}
