import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// Scripts run from the repo root (pnpm runs them at the package root), so
// vite's default root — the cwd — would be wrong. Anchor it to this file so
// index.html, src/ and the dist/ that tauri.conf points at all resolve here.
const appRoot = dirname(fileURLToPath(import.meta.url));

// @ts-expect-error process is a nodejs global
const host = process.env.TAURI_DEV_HOST;

// https://vite.dev/config/
export default defineConfig(async () => ({
  root: appRoot,
  plugins: [react()],

  build: {
    // Generated bytes live under the repo's build/ directory, never inside
    // apps/ — see README. emptyOutDir is required because this is outside
    // vite's root; it only ever wipes this dedicated directory.
    outDir: resolve(appRoot, "../../build/desktop/dist"),
    emptyOutDir: true,
  },

  // Vite options tailored for Tauri development and only applied in `tauri dev` or `tauri build`
  //
  // 1. prevent Vite from obscuring rust errors
  clearScreen: false,
  // 2. tauri expects a fixed port, fail if that port is not available
  server: {
    port: 1420,
    strictPort: true,
    host: host || false,
    hmr: host
      ? {
          protocol: "ws",
          host,
          port: 1421,
        }
      : undefined,
    watch: {
      // 3. tell Vite to ignore watching `src-tauri`
      ignored: ["**/src-tauri/**"],
    },
  },
}));
