pub mod app_launcher;
pub mod calculator;
pub mod clipboard_history;
pub mod file_search;
pub mod process_monitor;
pub mod system_commands;
pub mod web_search;
pub mod window_switcher;
pub mod workflows;
